WIFI_SSID="iotroam"
WIFI_PASSWORD="smart sensor systems"

MQTT_topic = "sensors/temperature"

HIVE_cluster_url="f30fffc2f4634495adba5b658610278c.s1.eu.hivemq.cloud"
HIVE_port = 8883
HIVE_username = "hivemq.webclient.1694888161785"
HIVE_password = "0132BHECmDiyzApq>;.,"
